Chat with us issue fixed on android
ExaThought/carparts-mobile-application pull request #11
Opened 2023-05-16 09:39 UTC by VaishakMB08

2023-05-17 06:26 UTC, nikitharajexathought requested changes

2023-05-17 06:26 UTC, nikitharajexathought commented on lib/src/web_view_stack.dart
> +            if (navigation.url.contains('tel')) {
move tel as a constant please

2023-05-17 06:26 UTC, nikitharajexathought commented on lib/src/web_view_stack.dart
> +                print("Cannot launch url");
why do we need this print statement?

2023-05-17 07:17 UTC, VaishakMB08 commented on lib/src/web_view_stack.dart
> +            if (navigation.url.contains('tel')) {
made changes

2023-05-17 07:18 UTC, VaishakMB08 commented on lib/src/web_view_stack.dart
> +                print("Cannot launch url");
removed print statement

2023-05-17 08:30 UTC, nikitharajexathought requested changes

2023-05-17 08:30 UTC, nikitharajexathought commented on lib/constants/navigation_constant.dart
> +  static const String facebook = "fb://page/";
whats the naing concention of constants? constats are always title case :)

2023-05-17 08:30 UTC, nikitharajexathought commented on lib/constants/navigation_constant.dart
> +class WebViewConstant {
name of the file and object should be plural, because we have multiple constants rigght?

2023-05-17 14:45 UTC, VaishakMB08 commented on lib/constants/navigation_constant.dart
> +  static const String facebook = "fb://page/";
changed the singular file name to plural

2023-05-17 14:46 UTC, VaishakMB08 commented on lib/constants/navigation_constant.dart
> +class WebViewConstant {
made changes

2023-05-22 09:29 UTC, nikitharajexathought approved these changes

2023-05-22 11:05 UTC, merged